apiVersion: v1
kind: Pod
metadata:
  name: conversao-temperatura
  labels:
    app: conversao-temperatura
spec:
  containers:
    - name: conversao-temperatura
      image:  maxamx/conversao-temperatura
      ports:
        - containerPort: 8080
